#ifndef _H_LGP_FLAGS_H
#define _H_LGP_FLAGS_H

//#define LGP_DEBUG
//#define LGP_BUILD_DEBUG

const int LGP_EXECUTE_NEXT_INSTRUCTION=0;
const int LGP_SKIP_NEXT_INSTRUCTION=1;

const unsigned int LGP_EVOLUTION_STRATEGY_STEADY_STATE=0;
const unsigned int LGP_EVOLUTION_STRATEGY_GENERATIONAL=1;

#endif